version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=synapsis_assignment
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - ./data:/var/lib/mysql
